name: Build and submit release version
on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  job_A:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.my_step.outputs.my_output }}
    steps:
      - name: Do something and generate output
        id: my_step
        run: |
          # Set an output variable called 'my_output'
          echo "name=my_output::Hello from Job A" >> $GITHUB_OUTPUT

  job_B:
    runs-on: ubuntu-latest
    needs: job_A
    permissions:
      issues: write

    steps:
      - name: Use the output from Job A
        run: |
          echo "The output from Job A is: ${{ needs.job_A.outputs.my_output }}" | ./post-new-issue.sh $GITHUB_REPOSITORY_OWNER $GITHUB_REPOSITORY
