name: Build and submit release version
on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  job_A:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.my_step.outputs.my_output }}
    steps:
      - name: Do something and generate output
        id: my_step
        run: |
          echo "name=Hello from Job A" >> $GITHUB_OUTPUT

  job_B:
    runs-on: ubuntu-latest
    needs: job_A
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use the output from Job A
        run: |
          echo "The output from Job A is: ${{ needs.job_A.outputs.name }}" | ./post-new-issue.sh $GITHUB_REPOSITORY
          echo "tagname=1.1.0" >> $GITHUB_OUTPUT

  job_C:
    runs-on: ubuntu-latest
    needs: [job_A, job_B]
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: make and push tag
        run: |
          git tag "v${{needs.job_B.outputs.tagname}}"
          git push origin tag "v${{needs.job_B.outputs.tagname}}"
