name: Issue to Release Tag

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}

on:
  workflow_dispatch: {}

jobs:
  # Job to create a release-tracking issue.
  create_issue:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Make a release plan
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Make plan
        run: |
          cat content | ./post-and-wait.sh "Release Plan" $GITHUB_REPOSITORY

      - name: Create and push the release tag
        run: |
          version=$(cat content)
          git tag "v$version"
          git push origin "v$version"

  deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: [create_issue]
    steps:
      - uses: actions/checkout@v4

      - run: echo BIBO
